# Generated by Django 5.0.3 on 2025-07-12 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_remove_exam_duration_minutes_exam_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexamattempt',
            name='start_time',
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
