# Generated by Django 5.0.3 on 2025-07-13 05:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_remove_studentexamattempt_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examassignment',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
