# Generated by Django 5.0.3 on 2025-07-21 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_examassignment_assigned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.student'),
        ),
        migrations.AlterField(
            model_name='studentexamattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.student'),
        ),
    ]
